// src/features/auth/infrastructure/ui/aluxLandingData.js

export const ALUX_DATA = {
  brandName: 'ALUX',
  brandSubtitle: 'CONSTRUCTORES EN ALUMINIO & VIDRIO',
  tagline: 'Diseñamos, fabricamos e instalamos soluciones que duran',
  heroTitle: 'TRANSFORMA TUS ESPACIOS CON ESTILO Y FUNCIONALIDAD',
  address: 'Av. Jacobo Bucaram y 25 de Diciembre',
  city: 'Milagro - Guayas - Ecuador',
  phone: '0985740242',
  whatsappPhone: '593985740242',
  socialHandle: '@alux_ec',
  stats: [
    { number: '+1.200', label: 'Proyectos Realizados', icon: 'Award' },
    { number: '+300', label: 'Empresas & Negocios Atendidos', icon: 'Building' },
    { number: '100%', label: 'Garantía en Trabajos', icon: 'ShieldCheck' },
    { number: '10+', label: 'Años de Experiencia', icon: 'Clock' },
  ],
  procesos: [
    {
      num: 1,
      titulo: 'Asesoría Personalizada',
      desc: 'Escuchamos tus ideas y analizamos tus necesidades en obra para ofrecerte la mejor solución técnica y estética.',
      icon: 'Users',
    },
    {
      num: 2,
      titulo: 'Diseño y Planificación',
      desc: 'Desarrollamos propuestas modernas, planos y despiece a la medida exacta de tus espacios.',
      icon: 'PenTool',
    },
    {
      num: 3,
      titulo: 'Fabricación en Taller',
      desc: 'Troquelado, corte y ensamblado utilizando perfiles de aluminio y vidrios templados certificados de alta calidad.',
      icon: 'Wrench',
    },
    {
      num: 4,
      titulo: 'Instalación Profesional',
      desc: 'Nuestro equipo realiza un montaje limpio, nivelado, seguro y eficiente en tu propiedad o local.',
      icon: 'CheckCircle',
    },
    {
      num: 5,
      titulo: 'Garantía y Respaldo',
      desc: 'Respaldamos cada trabajo con garantía directa, sellado de alta resistencia y atención postventa continua.',
      icon: 'Shield',
    },
  ],
  productos: [
    {
      id: 'ventanas',
      slug: 'ventanas-aluminio',
      nombre: 'Ventanas de Aluminio',
      categoria: 'Residencial & Comercial',
      desc: 'Ventanas corredizas, batientes y proyectables con excelente aislamiento térmico y acústico.',
      icon: 'LayoutGrid',
      tag: 'Alta Durabilidad',
      caracteristicas: ['Aislamiento térmico y acústico', 'Perfiles extruidos de alta resistencia', 'Cierres de seguridad de precisión'],
      image: '/assets/1.png',
    },
    {
      id: 'mamparas',
      slug: 'mamparas-vidrio',
      nombre: 'Mamparas & Divisiones de Vidrio',
      categoria: 'Oficinas & Comercio',
      desc: 'Mamparas fijas y móviles en vidrio templado para oficinas, locales y divisiones elegantes.',
      icon: 'Maximize',
      tag: 'Diseño Moderno',
      caracteristicas: ['Vidrio templado de 8mm y 10mm', 'Herrajes de acero inoxidable', 'Máxima entrada de luz natural'],
      image: '/assets/2.png',
    },
    {
      id: 'fachadas',
      slug: 'fachadas-alucobond',
      nombre: 'Fachadas en Alucobond (ACM)',
      categoria: 'Arquitectura Integral',
      desc: 'Revestimientos de fachadas comerciales e industriales en paneles de Alucobond y vidrio.',
      icon: 'Building2',
      tag: 'Imagen Corporativa',
      caracteristicas: ['Paneles de aluminio compuesto (ACM)', 'Resistentes a la intemperie y rayos UV', 'Diseño arquitectónico vanguardista'],
      image: '/assets/3.png',
    },
    {
      id: 'vitrinas',
      slug: 'vitrinas-comerciales',
      nombre: 'Vitrinas Comerciales',
      categoria: 'Locales & Negocios',
      desc: 'Exhibidores, aparadores y vitrinas modulares para destacar tus productos en punto de venta.',
      icon: 'Store',
      tag: 'Mayor Visibilidad',
      caracteristicas: ['Estructuras de aluminio anodizado', 'Vidrios pulidos y templados', 'Sistemas de iluminación LED opcionales'],
      image: '/assets/1.png',
    },
    {
      id: 'pergolas',
      slug: 'pergolas-modernas',
      nombre: 'Pérgolas Modernas & Policarbonato',
      categoria: 'Exteriores & Terrazas',
      desc: 'Pérgolas de aluminio estructural combinadas con cubiertas de policarbonato alveolar o compacto.',
      icon: 'Sun',
      tag: 'Protección UV',
      caracteristicas: ['Estructuras libres de corrosión', 'Protección solar y lluvia', 'Elegante integración arquitectónica'],
      image: '/assets/2.png',
    },
    {
      id: 'puertas',
      slug: 'puertas-residenciales',
      nombre: 'Puertas Residenciales & Corredizas',
      categoria: 'Interiores & Accesos',
      desc: 'Puertas de acceso principal, sistemas corredizos y abatibles en aluminio y cristal.',
      icon: 'DoorClosed',
      tag: 'Seguridad & Estilo',
      caracteristicas: ['Cierres herméticos de alta seguridad', 'Variedad de colores y acabados', 'Deslizamiento suave e insonoro'],
      image: '/assets/3.png',
    },
    {
      id: 'barandas',
      slug: 'barandas-pasamanos',
      nombre: 'Barandas & Pasamanos de Vidrio',
      categoria: 'Escaleras & Balcones',
      desc: 'Barandillas de vidrio templado con botones o soportes de acero inoxidable.',
      icon: 'Layers',
      tag: 'Máxima Elegancia',
      caracteristicas: ['Soportes en acero calidad 304', 'Vidrio de seguridad laminado/templado', 'Vista panorámica sin interrupciones'],
      image: '/assets/1.png',
    },
    {
      id: 'cerramientos',
      slug: 'cerramientos-techos',
      nombre: 'Cerramientos & Cubiertas',
      categoria: 'Protección Exterior',
      desc: 'Cerramientos integrales para patio, lavanderías y cubiertas transparentes o traslúcidas.',
      icon: 'Shield',
      tag: 'Resistencia Total',
      caracteristicas: ['Sellado estructural antihumedad', 'Soportes de aluminio reforzado', 'Bajo mantenimiento'],
      image: '/assets/2.png',
    },
    {
      id: 'espejos',
      slug: 'espejos-remodelacion',
      nombre: 'Espejos Decorativos & Remodelaciones',
      categoria: 'Interiores & Mantenimiento',
      desc: 'Espejos flotantes con iluminación, biselados y servicio técnico de mantenimiento.',
      icon: 'Sparkles',
      tag: 'Servicio Integral',
      caracteristicas: ['Biselado de precisión', 'Montaje con adhesivos neutros especiales', 'Remodelación y cambio de vidrios rotos'],
      image: '/assets/3.png',
    },
  ],
  beneficios: [
    {
      titulo: 'Materiales de Alta Calidad',
      desc: 'Perfiles de aluminio extruido y vidrio templado con estándares internacionales de durabilidad.',
      icon: 'Award',
    },
    {
      titulo: 'Diseños Modernos y Personalizados',
      desc: 'Creamos soluciones exactas adaptadas a las dimensiones y estética de tu espacio.',
      icon: 'PenTool',
    },
    {
      titulo: 'Instalación Profesional',
      desc: 'Personal técnico calificado con herramientas de precisión para acabados impecables.',
      icon: 'UserCheck',
    },
    {
      titulo: 'Entrega Puntual',
      desc: 'Respetamos estrictamente los plazos de fabricación e instalación acordados.',
      icon: 'Clock',
    },
    {
      titulo: 'Excelente Aislamiento',
      desc: 'Sistemas de sellado que minimizan ruido, filtraciones de agua y altas temperaturas.',
      icon: 'Shield',
    },
    {
      titulo: 'Garantía Directa en Obra',
      desc: 'Respaldo total en todos nuestros trabajos y atención postventa garantizada.',
      icon: 'CheckCircle2',
    },
  ],
};
